# Generated by Django 5.1.1 on 2025-01-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='patterns',
            field=models.CharField(choices=[('pattern 1', 'pattern 1'), ('pattern 2 ', 'pattern 2 ')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
